INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (1,'34''52','SADI Ali','Athletic Clubs 92*','M','092','M1M/79',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (2,'35''25','PREIRA William','Grand Paris Seine Oise Athle','M','078','M2M/75',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (3,'35''29','GRUNDTNER Willy','Ac Paris-joinville','M','094','M1M/79',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (4,'35''47','FAVIER Francois-rene','Paris Solon Athletic Academy','M','075','M2M/74',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (5,'35''52','RAYNAUD Bertrand','Cs Provins Athletisme','M','077','M1M/79',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (6,'35''55','ROUYER Thomas','Athletic Clubs 92*','M','092','M2M/73',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (7,'35''58','LECIEUX Thomas','Paris Solon Athletic Academy','M','075','M1M/79',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (8,'36''00','BROOKS Jerome','Es Sartrouville','M','078','M2M/73',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (9,'36''03','NARDI COLOME Franck','Us Ivry','M','094','M2M/74',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (10,'36''08','CHAREIL Ken','Pierrefitte Multi Athlon Ville','M','093','M1M/78',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (11,'36''35','ISMAEL Laurent','Athle 78 *','M','078','M1M/79',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (12,'36''36','KARA Amirouche','Athletic Clubs 92*','M','092','M1M/79',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (13,'36''37','DIANI Ilyas','Ac Paris-joinville','M','094','M1M/79',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (14,'36''38','CARANTON Laurent','Paris Solon Athletic Academy','M','075','M1M/76',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (15,'36''43','BENHAMOU Michael','Paris Solon Athletic Academy','M','075','M2M/73',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (16,'36''43','AIT IDER Mustapha','Team Lenglen Athletic Club','M','092','M1M/77',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (17,'36''47','MOUQUET Sylvain','Rambouillet Sports','M','078','M2M/71',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (18,'36''51','BEAUFORT Sebastien','Sporting Club Athletic De Bry-','M','094','M2M/75',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (19,'36''55','NEDELLEC Loic','Ea St Quentin En Yvelines','M','078','M1M/77',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (20,'36''59','BARGET Yann','Rambouillet Sports','M','078','M1M/79',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (21,'37''01','LEJEUNE Frank','Ac Du Pays De Meaux','M','077','M1M/79',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (22,'37''02','GRIBEAUVAL Ludovic','Ao Charenton','M','094','M1M/77',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (23,'37''04','GINER Wilfried','Rambouillet Sports','M','078','M2M/74',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (24,'37''13','CAILLOT Yannick','Grand Paris Seine Oise Athle','M','078','M1M/77',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (25,'37''14','EL YAMANI Mohammed','Team Lenglen Athletic Club','M','092','M4M/64',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (26,'37''17','LE BOUR Gael','Clamart Courses Sur Route 92','M','092','M1M/76',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (27,'37''19','ZEROUKI Mehdi-xavier','Paris Solon Athletic Academy','M','075','M2M/74',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (28,'37''19','MEGHAZI Mhamed','Senart Combs Brie Athletisme*','M','077','M2M/74',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (29,'37''36','MERROUNE Mohamed','Grand Paris Seine Oise Athle','M','078','M1M/76',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (30,'37''37','LACHEREST Sebastien','Dynamic Aulnay Club','M','093','M1M/78',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (31,'37''39','ABACHAD Adil','Ga Noisy Le Grand','M','093','M1M/77',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (32,'37''41','GUEGANO Raphael','Ac Velizy-villacoublay','M','078','M4M/65',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (33,'37''42','FELEMOU Athos','Us Metro Transport (paris)','M','075','M1M/80',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (34,'37''43','RENAUD Jean-claude','Us Torcy Athletisme','M','077','M1M/77',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (35,'37''43','LAHYANI Najib','Athle 91*','M','091','M1M/76',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (36,'37''47','BODIER Nicolas','Ga Noisy Le Grand','M','093','M1M/78',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (37,'37''47','MARTINHO Ezequiel','Dynamic Aulnay Club','M','093','M1M/78',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (38,'37''48','MAIRESSE Jean-baptiste','Fontenay Tresigny','M','077','M1M/76',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (39,'37''50','ZOETEMELK Karl','Bussy St Georges Athletisme','M','077','M2M/73',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (40,'37''52','RUIZ Pascal','Rambouillet Sports','M','078','M3M/69',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (41,'37''57','EL HAOUARI Rachid','Ga Noisy Le Grand','M','093','M2M/75',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (42,'38''01','LE KERVERN Pascal','Ga Noisy Le Grand','M','093','M1M/79',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (43,'38''24','OULD Fabien','Entente Franconville Cesame Va','M','095','M1M/78',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (44,'38''25','COURJAL Yannick','Stade Vertois Athletisme','M','091','M1M/79',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (45,'38''29','BARAONA Christophe','Athletic Clubs 92*','M','092','M1M/79',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (46,'38''34','BEN-HOUDJA Mohammed','Yerres Ac','M','091','M2M/72',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (47,'38''37','FARIA Rolando','Paris Solon Athletic Academy','M','075','M2M/73',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (48,'38''40','AUSTRUY Eric','Ao Charenton','M','094','M1M/80',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (49,'38''40','HARDY David','Ouest Essonne Athletisme','M','091','M2M/75',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (50,'38''44','HUE Sylvain','Ea St Quentin En Yvelines','M','078','M1M/76',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (51,'38''46','ALLONGUE Antoine','Ao Charenton','M','094','M1M/77',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (52,'38''47','DA SILVA Jose carlos','Entente Franconville Cesame Va','M','095','M2M/71',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (53,'38''48','VIOLARD Frederic','Ac Du Pays De Meaux','M','077','M1M/76',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (54,'38''48','ABDELKADER Yann','Ac Paris-joinville','M','094','M1M/77',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (55,'38''49','TOUPENAY Steve','Racing Multi Athlon','M','075','M2M/75',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (56,'38''50','CHERIFIA Farid','Racing Multi Athlon','M','075','M1M/80',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (57,'38''53','ANACHE Alexandre','Racing Multi Athlon','M','075','M2M/74',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (58,'38''57','ABDELMALEK Morad','Neuilly Sur Marne Athletisme','M','093','M1M/78',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (59,'39''00','WILLIATE Nicolas','Levallois Sc','M','092','M1M/76',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (60,'39''07','JARRY Alain','Rambouillet Sports','M','078','M2M/73',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (61,'39''07','GHIANI Marc','Racing Multi Athlon','M','075','M4M/65',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (62,'39''11','VIDAL Patrick','Les Foulees Breuilletoises','M','091','M3M/70',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (63,'39''12','VILFEU Ludovic','Grand Paris Seine Oise Athle','M','078','M2M/75',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (64,'39''12','BLANCHARD Nicolas','Uai Nogent-sur-marne','M','094','M1M/77',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (65,'39''13','COUSSEMENT Nicolas','Ua Versailles','M','078','M2M/75',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (66,'39''15','BADARD Christophe','Athle 92*','M','092','M1M/78',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (67,'39''15','BRIANT Geoffrey','Orsay Gif Athle*','M','091','M1M/76',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (68,'39''17','LEGER Franck','Sporting Club Athletic De Bry-','M','094','M1M/78',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (69,'39''20','DAUVILLIERS Sebastien','Elan 91*','M','091','M2M/73',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (70,'39''21','LEDOUX Daniel','Avon Athletisme Club','M','077','M1M/79',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (71,'39''21','SANCHEZ Christian','Ja Montrouge','M','075','M1M/76',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (72,'39''22','VERDOL Widdy','Livry Gargan Athletisme','M','093','M2M/75',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (73,'39''25','ANDRIEU Olivier','Ac Paris-joinville','M','094','M1M/78',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (74,'39''25','FORTUN Armel','Club Multi Sports De Pantin','M','093','M2M/75',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (75,'39''31','SAELEN Nicolas','Ea Cergy Pontoise Athletisme *','M','095','M1M/77',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (76,'39''33','QUEAU Christophe','Club Athletisme De Puteaux 92','M','092','M3M/68',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (77,'39''35','CATROU Olivier','Asphalte 94','M','094','M2M/71',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (78,'39''35','BENABDELKRIM Hicham','Neuilly Sur Marne Athletisme','M','093','M1M/79',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (79,'39''39','DURAND Jerome','Paris Uc','M','075','M2M/73',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (80,'39''40','COMPAIN Gaetan','Les Moustiques','M','075','M1M/80',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (81,'39''41','CROIZIER Lilian','Marne Et Gondoire Athletisme','M','077','M3M/67',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (82,'39''44','DA COSTA Bernard','Val D europe Athletisme','M','077','M2M/73',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (83,'39''48','HANNOUDI Mounir','Athletic Clubs 92*','M','092','M2M/73',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (84,'39''49','AUDEBERT Jean-philippe','Bussy St Georges Athletisme','M','077','M2M/75',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (85,'39''50','RAMZI Houcine','Athle 92*','M','092','M2M/73',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (86,'39''52','DUVERNE Guillaume','Rueil Ac','M','092','M1M/79',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (87,'39''53','MARCOVICI Jean-baptiste','Ao Charenton','M','094','M1M/77',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (88,'39''53','MARCHET Yann','Sam Paris 12','M','075','M2M/73',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (89,'39''56','OROBON Christophe','Grand Paris Seine Oise Athle','M','078','M1M/77',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (90,'39''56','MARTIN Thomas','Athletic Club Merevillois','M','091','M1M/78',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (91,'39''57','BUISSON Denis','C. O. Du Sud De L essonne','M','091','M3M/66',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (92,'39''59','BAUDRAS Damien','Ea Cergy Pontoise Athletisme *','M','095','M1M/77',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (93,'39''59','GARCIA SANCHEZ Jesus emilio','Ga Noisy Le Grand','M','093','M3M/69',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (94,'40''00','MONCHABLON Tristan','Athle 78 *','M','078','M1M/76',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (95,'40''01','SAGNA Aboudou','Rambouillet Sports','M','078','M2M/74',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (96,'40''03','IMAZATENE Ahmed','Tremblay Ac Athletisme','M','093','M1M/77',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (97,'40''04','HUMBERT Thierry','Grand Paris Seine Oise Athle','M','078','M2M/72',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (98,'40''09','DELAETER Fabrice','Paris Sport Club','M','075','M1M/80',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (99,'40''10','BEUCLAIR Nicolas','Vs Ozoir La Ferriere','M','077','M1M/77',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (100,'40''12','HENNI Djilali','Ao Charenton','M','094','M3M/66',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (101,'40''12','TASSIN Jerome','Rambouillet Sports','M','078','M2M/74',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (102,'40''14','GUINOISEAU Nicolas','Val D europe Athletisme','M','077','M1M/76',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (103,'40''15','ALEXANDRE Christian','Ea St Quentin En Yvelines','M','078','M4M/61',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (104,'40''17','PONCHEL Gregory','Union Athletique De Montereau','M','077','M2M/73',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (105,'40''18','NOIRY Julien','Ua Societe Generale','M','075','M1M/77',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (106,'40''20','MOURLON Nicolas','Athle 78 *','M','078','M1M/76',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (107,'40''22','DIOT Johann','Ac Du Pays De Meaux','M','077','M1M/80',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (108,'40''24','FERRAZ Antonio','Pontault Aac','M','077','M3M/68',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (109,'40''26','MATTERN Thibaut','Athletic Clubs 92*','M','092','M1M/77',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (110,'40''29','BAUDRY Bernard','Ac Du Pays De Meaux','M','077','M5M/59',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (111,'40''37','MOREAU Stephane','Paris Solon Athletic Academy','M','075','M2M/73',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (112,'40''38','BENHADDA Feth-allah','Union Sportive Alfortville Ath','M','094','M2M/75',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (113,'40''39','CURADO Pedro (Por)','Ga Noisy Le Grand','M','093','M2M/72',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (114,'40''40','PAINEAU Nicolas','Marne Et Gondoire Athletisme','M','077','M3M/66',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (115,'40''41','DRAY Sebastien','Grand Paris Seine Oise Athle','M','078','M1M/76',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (116,'40''42','DUPRE Franck','Pays De Nemours Running Trail','M','077','M2M/71',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (117,'40''45','ROSSE Sebastien','Team Lenglen Athletic Club','M','092','M2M/71',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (118,'40''45','ADAO Manuel','Villemomble Sports','M','093','M2M/71',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (119,'40''48','ALIX Herve','Ac Du Pays De Meaux','M','077','M1M/78',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (120,'40''49','LAMINE Moustapha (Mar)','Csm Bonneuil Sur Marne','M','094','M3M/68',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (121,'40''50','ARMAND Gilles','Association Chelles Champs Ath','M','077','M2M/75',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (122,'40''51','AHMIMID M hamed','Les Furets D Eiffage','M','078','M2M/72',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (123,'40''53','JIMENEZ Simon','Lisses Ac','M','091','M1M/77',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (124,'40''55','GRANGER David','Dynamic Aulnay Club','M','093','M1M/76',99,'lifa', 2020);
INSERT INTO cros (rang, chrono, nom, club, sexe, dep, cat, naissance, championnat, annee) VALUES (125,'40''56','LE QUERRE Fabrice','Clamart Courses Sur Route 92','M','092','M2M/72',99,'lifa', 2020);