INSERT INTO pays (id, code, nom) values (1,'AFG',' Afghanistan');
INSERT INTO pays (id, code, nom) values (2,'ALB',' Albanie');
INSERT INTO pays (id, code, nom) values (3,'ALG',' Algérie');
INSERT INTO pays (id, code, nom) values (4,'AND',' Andorre');
INSERT INTO pays (id, code, nom) values (5,'ANG',' Angola');
INSERT INTO pays (id, code, nom) values (6,'ANT',' Antigua-et-Barbuda');
INSERT INTO pays (id, code, nom) values (7,'ARG',' Argentine');
INSERT INTO pays (id, code, nom) values (8,'ARM',' Arménie');
INSERT INTO pays (id, code, nom) values (9,'ARU',' Aruba');
INSERT INTO pays (id, code, nom) values (10,'ASA',' Samoa américaines');
INSERT INTO pays (id, code, nom) values (11,'AUS',' Australie (1952–)');
INSERT INTO pays (id, code, nom) values (12,'AUT',' Autriche (1952–)');
INSERT INTO pays (id, code, nom) values (13,'AZE',' Azerbaïdjan');
INSERT INTO pays (id, code, nom) values (14,'BAH',' Bahamas');
INSERT INTO pays (id, code, nom) values (15,'BAN',' Bangladesh');
INSERT INTO pays (id, code, nom) values (16,'BAR',' Barbade (1968–)');
INSERT INTO pays (id, code, nom) values (17,'BDI',' Burundi');
INSERT INTO pays (id, code, nom) values (18,'BEL',' Belgique (1952–)');
INSERT INTO pays (id, code, nom) values (19,'BEN',' Bénin  Bénin (1984–)');
INSERT INTO pays (id, code, nom) values (20,'BER',' Bermudes');
INSERT INTO pays (id, code, nom) values (21,'BHU',' Bhoutan');
INSERT INTO pays (id, code, nom) values (22,'BIH',' Bosnie-Herzégovine');
INSERT INTO pays (id, code, nom) values (23,'BIZ',' Belize (1976–)');
INSERT INTO pays (id, code, nom) values (24,'BLR',' Biélorussie (1996–)');
INSERT INTO pays (id, code, nom) values (25,'BOL',' Bolivie');
INSERT INTO pays (id, code, nom) values (26,'BOT',' Botswana');
INSERT INTO pays (id, code, nom) values (27,'BRA',' Brésil');
INSERT INTO pays (id, code, nom) values (28,'BRN',' Bahreïn');
INSERT INTO pays (id, code, nom) values (29,'BRU',' Brunei');
INSERT INTO pays (id, code, nom) values (30,'BUL',' Bulgarie');
INSERT INTO pays (id, code, nom) values (31,'BUR',' Burkina Faso');
INSERT INTO pays (id, code, nom) values (32,'CAF',' République centrafricaine');
INSERT INTO pays (id, code, nom) values (33,'CAM',' Cambodge');
INSERT INTO pays (id, code, nom) values (34,'CAN',' Canada');
INSERT INTO pays (id, code, nom) values (35,'CAY',' Îles Caïmans');
INSERT INTO pays (id, code, nom) values (36,'CGO',' République du Congo');
INSERT INTO pays (id, code, nom) values (37,'CHA',' Tchad');
INSERT INTO pays (id, code, nom) values (38,'CHI',' Chili');
INSERT INTO pays (id, code, nom) values (39,'CHN',' Chine, République populaire de');
INSERT INTO pays (id, code, nom) values (40,'CIV',' Côte d Ivoire');
INSERT INTO pays (id, code, nom) values (41,'CMR',' Cameroun');
INSERT INTO pays (id, code, nom) values (42,'COD',' République démocratique du Congo');
INSERT INTO pays (id, code, nom) values (43,'COK',' Îles Cook');
INSERT INTO pays (id, code, nom) values (44,'COL',' Colombie');
INSERT INTO pays (id, code, nom) values (45,'COM',' Comores');
INSERT INTO pays (id, code, nom) values (46,'CPV',' Cap-Vert');
INSERT INTO pays (id, code, nom) values (47,'CRC',' Costa Rica');
INSERT INTO pays (id, code, nom) values (48,'CRO',' Croatie');
INSERT INTO pays (id, code, nom) values (49,'CUB',' Cuba');
INSERT INTO pays (id, code, nom) values (50,'CYP',' Chypre');
INSERT INTO pays (id, code, nom) values (51,'CZE',' République tchèque');
INSERT INTO pays (id, code, nom) values (52,'DEN',' Danemark');
INSERT INTO pays (id, code, nom) values (53,'DJI',' Djibouti');
INSERT INTO pays (id, code, nom) values (54,'DMA',' Dominique');
INSERT INTO pays (id, code, nom) values (55,'DOM',' République dominicaine');
INSERT INTO pays (id, code, nom) values (56,'ECU',' Équateur');
INSERT INTO pays (id, code, nom) values (57,'EGY',' Égypte');
INSERT INTO pays (id, code, nom) values (58,'ERI',' Érythrée');
INSERT INTO pays (id, code, nom) values (59,'ESA',' Salvador');
INSERT INTO pays (id, code, nom) values (60,'ESP',' Espagne');
INSERT INTO pays (id, code, nom) values (61,'EST',' Estonie');
INSERT INTO pays (id, code, nom) values (62,'ETH',' Éthiopie');
INSERT INTO pays (id, code, nom) values (63,'FIJ',' Fidji');
INSERT INTO pays (id, code, nom) values (64,'FIN',' Finlande');
INSERT INTO pays (id, code, nom) values (65,'FRA',' France');
INSERT INTO pays (id, code, nom) values (66,'FSM',' Micronésie');
INSERT INTO pays (id, code, nom) values (67,'GAB',' Gabon');
INSERT INTO pays (id, code, nom) values (68,'GAM',' Gambie');
INSERT INTO pays (id, code, nom) values (69,'GBR',' Royaume-Uni');
INSERT INTO pays (id, code, nom) values (70,'GBS',' Guinée-Bissau');
INSERT INTO pays (id, code, nom) values (71,'GEO',' Géorgie');
INSERT INTO pays (id, code, nom) values (72,'GEQ',' Guinée équatoriale');
INSERT INTO pays (id, code, nom) values (73,'GER',' Allemagne');
INSERT INTO pays (id, code, nom) values (74,'GHA',' Ghana');
INSERT INTO pays (id, code, nom) values (75,'GRE',' Grèce');
INSERT INTO pays (id, code, nom) values (76,'GRN',' Grenade');
INSERT INTO pays (id, code, nom) values (77,'GUA',' Guatemala');
INSERT INTO pays (id, code, nom) values (78,'GUI',' Guinée');
INSERT INTO pays (id, code, nom) values (79,'GUM',' Guam');
INSERT INTO pays (id, code, nom) values (80,'GUY',' Guyana');
INSERT INTO pays (id, code, nom) values (81,'HAI',' Haïti');
INSERT INTO pays (id, code, nom) values (82,'HKG',' Hong Kong');
INSERT INTO pays (id, code, nom) values (83,'HON',' Honduras');
INSERT INTO pays (id, code, nom) values (84,'HUN',' Hongrie');
INSERT INTO pays (id, code, nom) values (85,'INA',' Indonésie');
INSERT INTO pays (id, code, nom) values (86,'IND',' Inde');
INSERT INTO pays (id, code, nom) values (87,'IOA',' Athlètes olympiques internationaux');
INSERT INTO pays (id, code, nom) values (88,'IRI',' Iran');
INSERT INTO pays (id, code, nom) values (89,'IRL',' Irlande');
INSERT INTO pays (id, code, nom) values (90,'IRQ',' Irak');
INSERT INTO pays (id, code, nom) values (91,'ISL',' Islande');
INSERT INTO pays (id, code, nom) values (92,'ISR',' Israël');
INSERT INTO pays (id, code, nom) values (93,'ISV',' Îles Vierges des États-Unis');
INSERT INTO pays (id, code, nom) values (94,'ITA',' Italie');
INSERT INTO pays (id, code, nom) values (95,'IVB',' Îles Vierges britanniques');
INSERT INTO pays (id, code, nom) values (96,'JAM',' Jamaïque');
INSERT INTO pays (id, code, nom) values (97,'JOR',' Jordanie');
INSERT INTO pays (id, code, nom) values (98,'JPN',' Japon');
INSERT INTO pays (id, code, nom) values (99,'KAZ',' Kazakhstan');
INSERT INTO pays (id, code, nom) values (100,'KEN',' Kenya');
INSERT INTO pays (id, code, nom) values (101,'KGZ',' Kirghizistan');
INSERT INTO pays (id, code, nom) values (102,'KIR',' Kiribati');
INSERT INTO pays (id, code, nom) values (103,'KOS',' Kosovo');
INSERT INTO pays (id, code, nom) values (104,'KOR',' Corée du Sud (République de Corée)');
INSERT INTO pays (id, code, nom) values (105,'KSA',' Arabie saoudite');
INSERT INTO pays (id, code, nom) values (106,'KUW',' Koweït');
INSERT INTO pays (id, code, nom) values (107,'LAO',' Laos (République démocratique populaire lao)');
INSERT INTO pays (id, code, nom) values (108,'LAT',' Lettonie');
INSERT INTO pays (id, code, nom) values (109,'LBA',' Libye');
INSERT INTO pays (id, code, nom) values (110,'LBR',' Liberia');
INSERT INTO pays (id, code, nom) values (111,'LCA',' Sainte-Lucie');
INSERT INTO pays (id, code, nom) values (112,'LES',' Lesotho');
INSERT INTO pays (id, code, nom) values (113,'LIB',' Liban');
INSERT INTO pays (id, code, nom) values (114,'LIE',' Liechtenstein');
INSERT INTO pays (id, code, nom) values (115,'LTU',' Lituanie');
INSERT INTO pays (id, code, nom) values (116,'LUX',' Luxembourg');
INSERT INTO pays (id, code, nom) values (117,'MAD',' Madagascar');
INSERT INTO pays (id, code, nom) values (118,'MAR',' Maroc');
INSERT INTO pays (id, code, nom) values (119,'MAS',' Malaisie');
INSERT INTO pays (id, code, nom) values (120,'MAW',' Malawi');
INSERT INTO pays (id, code, nom) values (121,'MDA',' Moldavie');
INSERT INTO pays (id, code, nom) values (122,'MDV',' Maldives');
INSERT INTO pays (id, code, nom) values (123,'MEX',' Mexique');
INSERT INTO pays (id, code, nom) values (124,'MGL',' Mongolie');
INSERT INTO pays (id, code, nom) values (125,'MHL',' Îles Marshall');
INSERT INTO pays (id, code, nom) values (126,'MKD',' Macédoine, ex-république yougoslave de');
INSERT INTO pays (id, code, nom) values (127,'MLI',' Mali');
INSERT INTO pays (id, code, nom) values (128,'MLT',' Malte');
INSERT INTO pays (id, code, nom) values (129,'MNE',' Monténégro');
INSERT INTO pays (id, code, nom) values (130,'MON',' Monaco');
INSERT INTO pays (id, code, nom) values (131,'MOZ',' Mozambique');
INSERT INTO pays (id, code, nom) values (132,'MRI',' Maurice');
INSERT INTO pays (id, code, nom) values (133,'MTN',' Mauritanie');
INSERT INTO pays (id, code, nom) values (134,'MYA',' Birmanie (Myanmar)');
INSERT INTO pays (id, code, nom) values (135,'NAM',' Namibie');
INSERT INTO pays (id, code, nom) values (136,'NCA',' Nicaragua');
INSERT INTO pays (id, code, nom) values (137,'NED',' Pays-Bas');
INSERT INTO pays (id, code, nom) values (138,'NEP',' Népal');
INSERT INTO pays (id, code, nom) values (139,'NGR',' Nigeria');
INSERT INTO pays (id, code, nom) values (140,'NIG',' Niger');
INSERT INTO pays (id, code, nom) values (141,'NOR',' Norvège');
INSERT INTO pays (id, code, nom) values (142,'NRU',' Nauru');
INSERT INTO pays (id, code, nom) values (143,'NZL',' Nouvelle-Zélande');
INSERT INTO pays (id, code, nom) values (144,'OMA',' Oman');
INSERT INTO pays (id, code, nom) values (145,'PAK',' Pakistan');
INSERT INTO pays (id, code, nom) values (146,'PAN',' Panama');
INSERT INTO pays (id, code, nom) values (147,'PAR',' Paraguay');
INSERT INTO pays (id, code, nom) values (148,'PER',' Pérou');
INSERT INTO pays (id, code, nom) values (149,'PHI',' Philippines');
INSERT INTO pays (id, code, nom) values (150,'PLE',' Palestine');
INSERT INTO pays (id, code, nom) values (151,'PLW',' Palaos');
INSERT INTO pays (id, code, nom) values (152,'PNG',' Papouasie-Nouvelle-Guinée');
INSERT INTO pays (id, code, nom) values (153,'POL',' Pologne');
INSERT INTO pays (id, code, nom) values (154,'POR',' Portugal');
INSERT INTO pays (id, code, nom) values (155,'PRK',' Corée du Nord (République populaire démocratique de Corée)');
INSERT INTO pays (id, code, nom) values (156,'PUR',' Porto Rico');
INSERT INTO pays (id, code, nom) values (157,'QAT',' Qatar');
INSERT INTO pays (id, code, nom) values (158,'ROT',' Équipe olympique des réfugiés');
INSERT INTO pays (id, code, nom) values (159,'ROU',' Roumanie');
INSERT INTO pays (id, code, nom) values (160,'RSA',' Afrique du Sud');
INSERT INTO pays (id, code, nom) values (161,'RUS',' Russie, Fédération de');
INSERT INTO pays (id, code, nom) values (162,'RWA',' Rwanda');
INSERT INTO pays (id, code, nom) values (163,'SAM',' Samoa');
INSERT INTO pays (id, code, nom) values (164,'SEN',' Sénégal');
INSERT INTO pays (id, code, nom) values (165,'SEY',' Seychelles');
INSERT INTO pays (id, code, nom) values (166,'SIN',' Singapour');
INSERT INTO pays (id, code, nom) values (167,'SKN',' Saint-Christophe-et-Niévès (Saint-Kitts-et-Nevis)');
INSERT INTO pays (id, code, nom) values (168,'SLE',' Sierra Leone');
INSERT INTO pays (id, code, nom) values (169,'SLO',' Slovénie');
INSERT INTO pays (id, code, nom) values (170,'SMR',' Saint-Marin');
INSERT INTO pays (id, code, nom) values (171,'SOL',' Salomon');
INSERT INTO pays (id, code, nom) values (172,'SOM',' Somalie');
INSERT INTO pays (id, code, nom) values (173,'SRB',' Serbie');
INSERT INTO pays (id, code, nom) values (174,'SRI',' Sri Lanka');
INSERT INTO pays (id, code, nom) values (175,'SSD',' Soudan du Sud');
INSERT INTO pays (id, code, nom) values (176,'STP',' Sao Tomé-et-Principe');
INSERT INTO pays (id, code, nom) values (177,'SUD',' Soudan');
INSERT INTO pays (id, code, nom) values (178,'SUI',' Suisse');
INSERT INTO pays (id, code, nom) values (179,'SUR',' Suriname');
INSERT INTO pays (id, code, nom) values (180,'SVK',' Slovaquie');
INSERT INTO pays (id, code, nom) values (181,'SWE',' Suède');
INSERT INTO pays (id, code, nom) values (182,'SWZ',' Swaziland');
INSERT INTO pays (id, code, nom) values (183,'SYR',' Syrie (République arabe syrienne)');
INSERT INTO pays (id, code, nom) values (184,'TAN',' Tanzanie, République unie de');
INSERT INTO pays (id, code, nom) values (185,'TGA',' Tonga');
INSERT INTO pays (id, code, nom) values (186,'THA',' Thaïlande');
INSERT INTO pays (id, code, nom) values (187,'TJK',' Tadjikistan');
INSERT INTO pays (id, code, nom) values (188,'TKM',' Turkménistan');
INSERT INTO pays (id, code, nom) values (189,'TLS',' Timor oriental (Timor-Leste)');
INSERT INTO pays (id, code, nom) values (190,'TOG',' Togo');
INSERT INTO pays (id, code, nom) values (191,'TPE',' Taipei chinois');
INSERT INTO pays (id, code, nom) values (192,'TTO3',' Trinité-et-Tobago');
INSERT INTO pays (id, code, nom) values (193,'TUN',' Tunisie');
INSERT INTO pays (id, code, nom) values (194,'TUR',' Turquie');
INSERT INTO pays (id, code, nom) values (195,'TUV',' Tuvalu');
INSERT INTO pays (id, code, nom) values (196,'UAE',' Émirats arabes unis');
INSERT INTO pays (id, code, nom) values (197,'UGA',' Ouganda');
INSERT INTO pays (id, code, nom) values (198,'UKR',' Ukraine');
INSERT INTO pays (id, code, nom) values (199,'URU',' Uruguay');
INSERT INTO pays (id, code, nom) values (200,'USA',' États-Unis');
INSERT INTO pays (id, code, nom) values (201,'UZB',' Ouzbékistan');
INSERT INTO pays (id, code, nom) values (202,'VAN',' Vanuatu');
INSERT INTO pays (id, code, nom) values (203,'VEN',' Venezuela');
INSERT INTO pays (id, code, nom) values (204,'VIE',' Viêt Nam');
INSERT INTO pays (id, code, nom) values (205,'VIN',' Saint-Vincent-et-les Grenadines');
INSERT INTO pays (id, code, nom) values (206,'YEM',' Yémen');
INSERT INTO pays (id, code, nom) values (207,'ZAM',' Zambie');
INSERT INTO pays (id, code, nom) values (208,'ZIM',' Zimbabwe');


